AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template used for showcasing AWS AppConfig feature flags

Parameters:
  AppName:
    Type: String
    Description: "Name of application associated with AppConfig instance."
    AllowedPattern: ".+"

  CostCenter:
    Type: String
    Description: "Department responsible for billing of AppConfig instance."
    AllowedPattern: ".+"

Resources:
  AppConfigInstance:
    Type: AWS::AppConfig::Application
    Properties:
      Name: !Ref AppName
      Description: !Sub "AppConfig instance containing all configuration for ${AppName}"
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: APP_NAME
          Value: !Ref AppName

  # Environments
  DevEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      Name: "dev"
      Description: !Sub "Dev environment for ${AppName}"
      ApplicationId: !Ref AppConfigInstance
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: ENVIRONMENT
          Value: "dev"
        - Key: APP_NAME
          Value: !Ref AppName

  StgEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      Name: "stg"
      Description: !Sub "Stg environment for ${AppName}"
      ApplicationId: !Ref AppConfigInstance
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: ENVIRONMENT
          Value: "stg"
        - Key: APP_NAME
          Value: !Ref AppName

  PrdEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      Name: "prd"
      Description: !Sub "PRD environment for ${AppName}"
      ApplicationId: !Ref AppConfigInstance
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: ENVIRONMENT
          Value: "prd"
        - Key: APP_NAME
          Value: !Ref AppName

  # Configuration Profile
  Milestone0ConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigInstance
      Name: !Sub "milestone0-profile"
      Description: "Configuration profile for Milestone0"
      LocationUri: hosted
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: ENVIRONMENT
          Value: "prd"
        - Key: APP_NAME
          Value: !Ref AppName

  Milestone1ConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigInstance
      Name: !Sub "milestone1-profile"
      Description: "Configuration profile for Milestone1"
      LocationUri: hosted
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: ENVIRONMENT
          Value: "prd"
        - Key: APP_NAME
          Value: !Ref AppName

  # Feature Flags
  EnableMilestone0:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref AppConfigInstance
      ConfigurationProfileId: !Ref Milestone0ConfigProfile
      Description: "Freeform config for Milestone0"
      Content: !Sub |
        {
          "feature": {
            "enabled": false,
            "limit": 10
          }
        }
      ContentType: "application/json"

  EnableMilestone1:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref AppConfigInstance
      ConfigurationProfileId: !Ref Milestone1ConfigProfile
      Description: "Freeform config used for Milestone1"
      Content: !Sub |
        {
          "feature": {
            "enabled": true,
            "limit": 100
          }
        }
      ContentType: "application/json"

  # Deployment Strategies
  QuickSwapDeploymentStrategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      Name: "AllAtOnce.ImmediateSwap"
      Description: "Deployment strategy used for immediate swapping of configuration"
      DeploymentDurationInMinutes: 0
      FinalBakeTimeInMinutes: 0
      GrowthFactor: 100
      GrowthType: LINEAR
      ReplicateTo: NONE
      Tags:
        - Key: COST_CENTER
          Value: !Ref CostCenter
        - Key: ENVIRONMENT
          Value: "prd"
        - Key: APP_NAME
          Value: !Ref AppName

  # Deploy to environments
  DevConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref AppConfigInstance
      ConfigurationProfileId: !Ref Milestone1ConfigProfile
      ConfigurationVersion: !Ref EnableMilestone1
      DeploymentStrategyId: !Ref QuickSwapDeploymentStrategy
      EnvironmentId: !Ref DevEnvironment

  StgConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref AppConfigInstance
      ConfigurationProfileId: !Ref Milestone0ConfigProfile
      ConfigurationVersion: !Ref EnableMilestone0
      DeploymentStrategyId: !Ref QuickSwapDeploymentStrategy
      EnvironmentId: !Ref StgEnvironment

  PrdConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref AppConfigInstance
      ConfigurationProfileId: !Ref Milestone0ConfigProfile
      ConfigurationVersion: !Ref EnableMilestone0
      DeploymentStrategyId: !Ref QuickSwapDeploymentStrategy
      EnvironmentId: !Ref PrdEnvironment